### ISSUE TITLE
code block cannot auto overflow or word break

### ISSUE THREAD

**Issue by zixuanweeei** [artemsheludko/flexible-jekyll#25]

**Comment by artemsheludko** [comment]
@zixuanweeei Hi, could you describe the error in more detail?

**Comment by gcbeen** [comment]
@artemsheludko code block ,too long code meet

**Comment by artemsheludko** [comment]
@zixuanweeei @gcbeen, I fixed it, thank you.

**Comment by Blafy** [comment]
Thanks for thix and this nice theme @artemsheludko !
Although I think the the same kind of issue is still present with the mobile layout, cf [this page](https://goo.gl/esgP7F) (Sorry about the URL shortener but I don't want to mention this URL here).
The article width cannot be smaller than the code block

**Comment by Blafy** [comment]
Thanks for the thix and this nice theme @artemsheludko !
Although I think the the same kind of issue is still present with the mobile layout, cf [this page](https://huit.re/0fLDwwqV) (Sorry about the URL shortener, but I don't want to mention this URL here).
The article width cannot be smaller than the code block

**Comment by Blafy** [comment]
Thanks for the fix and this nice theme @artemsheludko !
Although I think the the same kind of issue is still present with the mobile layout, cf [this page](https://huit.re/0fLDwwqV) (Sorry about the URL shortener, but I don't want to mention this URL here).
The article width cannot be smaller than the code block

**Comment by artemsheludko** [comment]
@Blafy Not compiled main.scss file. Fixed, will now work on mobile devices. Thank you!
